### ISSUE TITLE
文件损坏无法播放

### ISSUE THREAD

**Issue by darkfiredarkhalo** [ZeroOnet/ZonPlayer#3]
`ZonPlayer.player(url)
                .cache(ZonPlayer.Cache.Streaming(source: ZPC.DefaultStreamingSource(enableConsoleLog: true)))`
 开启缓存后, 很容易出现缓存后的文件比实际文件大的情况, 造成文件损坏
`playerTerminated(A player error occurred: Error Domain=AVFoundationErrorDomain Code=-11829 "Cannot Open" UserInfo={NSLocalizedFailureReason=This media may be damaged., NSLocalizedDescription=Cannot Open, NSUnderlyingError=0x600000da0120 {Error Domain=NSOSStatusErrorDomain Code=-12848 "(null)"}}.)`

**Comment by darkfiredarkhalo** [comment]
尤其是阿里云oss上的视频文件
如下异常:
![image](https://github.com/ZeroOnet/ZonPlayer/assets/13959162/35243935-d5eb-4eab-bf10-ff7fb6a6396e)
![image](https://github.com/ZeroOnet/ZonPlayer/assets/13959162/5820134e-4e70-43b5-a723-e0f7ca428408)

**Comment by ZeroOnet** [comment]
> 尤其是阿里云oss上的视频文件 如下异常: ![image](https://private-user-images.githubusercontent.com/13959162/338854224-35243935-d5eb-4eab-bf10-ff7fb6a6396e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNDUyNTcsIm5iZiI6MTcxODI0NDk1NywicGF0aCI6Ii8xMzk1OTE2Mi8zMzg4NTQyMjQtMzUyNDM5MzUtZDVlYi00ZWFiLWJmMTAtZmY3ZmI2YTYzOTZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDAyMTU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5N2ViY2RkNjAwNjFlNDJkOTJmZGYxZTRhMDUyZjZjYmExYTllMDlhYTIxMDc5MmJmN2Q4YjQ0MzA5YmM2ZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0OFg_FDl4lw4d-v7_8T-g8SeMIVJf_G3PyLvPqAqkzs) ![image](https://private-user-images.githubusercontent.com/13959162/338854674-5820134e-4e70-43b5-a723-e0f7ca428408.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNDUyNTcsIm5iZiI6MTcxODI0NDk1NywicGF0aCI6Ii8xMzk1OTE2Mi8zMzg4NTQ2NzQtNTgyMDEzNGUtNGU3MC00M2I1LWE3MjMtZTBmN2NhNDI4NDA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDAyMTU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwMjcyNmJkMjc5MmNjOTc1ZTM0ZjJhYzAxNGRlZTEwM2ExYmE1YzE2OTczOWQwMTY4NTdhZGI2NzRiMGQ4ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wXLLT0mDURDGPko8p9vhIGHrTgww9kb4omrEXMVbUdg)

感谢反馈~ 我这边先排查一下，你这边方便提供一个可以复现问题的 URL 吗？@darkfiredarkhalo

**Comment by ZeroOnet** [comment]
在分析了你的这张截图之后，发现你所使用的 URL 不支持 byte range access，即 isByteRangeAccessSupported 为 false，这可能导致了 AVPlayer 无法实现边下边播。你可以先尝试让 URL 支持这一特性，观察问题是否解决，我这边研究下是否有兼容手段可以实施。

> Before finishing loading an [AVAssetResourceLoadingRequest](https://developer.apple.com/documentation/avfoundation/avassetresourceloadingrequest) instance, if its [contentInformationRequest](https://developer.apple.com/documentation/avfoundation/avassetresourceloadingrequest/1390340-contentinformationrequest) property is not nil, set the value of this property to true if it supports random access to arbitrary ranges of bytes of the resource.
If this property is not true for resources that must be loaded incrementally, loading of the resource may fail. Such resources include anything that contains media data.
If byte range access is supported portions of the resource can be requested more than once.

**Comment by darkfiredarkhalo** [comment]
> 感谢反馈~ 我这边先排查一下，你这边方便提供一个可以复现问题的 URL 吗？@darkfiredarkhalo

@ZeroOnet  你好, 非常感谢, 可以使用这个URL: `https://welink-games-test.oss-cn-zhangjiakou.aliyuncs.com/0-wjn-ARCX/20240611-174634.mp4`, 刚在oss文档上看了, 他是支持rang请求的, 如下描述:
![image](https://github.com/ZeroOnet/ZonPlayer/assets/13959162/a11ae7e8-ced3-4e16-91ca-89357d4ed208)
断点查看`metaData`中的`isByteRangeAccessSupported`也是`true`  
在浏览器中直接访问以上url, 可以看到它是`rang`请求的,但是这个`rang`有重合的...
在源码中追踪看, 好像只要触发了`func resourceLoader(_ resourceLoader: AVAssetResourceLoader, didCancel loadingRequest: AVAssetResourceLoadingRequest )`, 就会出现异常`rang`的请求, 这些异常请求的结果会被直接追加到缓存文件中, 造成文件损坏...
可能需要有个逻辑来处理`rang`重合的这种情形, 我这也正在研究你的代码,☺️

**Comment by darkfiredarkhalo** [comment]
只要去掉`.cache()`, 播放器是能正常播放的, 即使是oss上的大视频也可以很快开始播放

**Comment by ZeroOnet** [comment]
> > 感谢反馈~ 我这边先排查一下，你这边方便提供一个可以复现问题的 URL 吗？@darkfiredarkhalo
> 
> @ZeroOnet 你好, 非常感谢, 可以使用这个URL: `https://welink-games-test.oss-cn-zhangjiakou.aliyuncs.com/0-wjn-ARCX/20240611-174634.mp4`, 刚在oss文档上看了, 他是支持rang请求的, 如下描述: ![image](https://private-user-images.githubusercontent.com/13959162/339266052-a11ae7e8-ced3-4e16-91ca-89357d4ed208.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMzA5NjcsIm5iZiI6MTcxODMzMDY2NywicGF0aCI6Ii8xMzk1OTE2Mi8zMzkyNjYwNTItYTExYWU3ZTgtY2VkMy00ZTE2LTkxY2EtODkzNTdkNGVkMjA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDAyMDQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmNDVkMjYwNmU2YjdjMGQ1NjM0ODNiNDkwOWM0NmQyMjI1YjczZmFiNzlhZWE5NjJhZjQ2NTUzNTIyOTFjMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T_gynjrt3Fio19z7H2sNBXH-PvBd3wCBuEmFd9vFaB4) 断点查看`metaData`中的`isByteRangeAccessSupported`也是`true` 在浏览器中直接访问以上url, 可以看到它是`rang`请求的,但是这个`rang`有重合的... 在源码中追踪看, 好像只要触发了`func resourceLoader(_ resourceLoader: AVAssetResourceLoader, didCancel loadingRequest: AVAssetResourceLoadingRequest )`, 就会出现异常`rang`的请求, 这些异常请求的结果会被直接追加到缓存文件中, 造成文件损坏... 可能需要有个逻辑来处理�`rang`重合的这种情形, 我这也正在研究你的代码,☺️

好的，我周末的时候看一下。

**Comment by ZeroOnet** [comment]
@darkfiredarkhalo 你试试 bugfix/segmented-data 这个分支，看问题是否已经解决？

**Comment by darkfiredarkhalo** [comment]
> @darkfiredarkhalo 你试试 bugfix/segmented-data 这个分支，看问题是否已经解决？

不好意思,这么多天才回复....    
缓存的问题已经好了👍🏻
不过在播放长视频的时候有一定的几率会遇到`ZonPlayer did wait to play: AVPlayerWaitingToMinimizeStallsReason.`这种情形, 造成播放卡住了, 需要暂停重新play
